# Generated by Django 3.1.5 on 2021-11-25 22:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210623_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File Upload'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
